# Generated by Django 3.1 on 2020-08-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_teacher',
            field=models.BooleanField(blank=True, default=False, verbose_name='Учитель?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(upload_to='user_img/', verbose_name='Фото'),
        ),
    ]
