# Generated by Django 3.1 on 2020-08-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0002_auto_20200818_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название курса')),
                ('course_img', models.ImageField(upload_to='course_img/', verbose_name='Превью')),
                ('course_teacher', models.ManyToManyField(to='WebAlgorithm.Profile')),
            ],
        ),
    ]
