# Generated by Django 3.1 on 2020-08-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0003_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(blank=True, upload_to='user_img/', verbose_name='Фото'),
        ),
    ]
