# Generated by Django 3.1 on 2020-08-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0004_auto_20200818_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, upload_to='course_img/', verbose_name='Превью'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='course_teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='WebAlgorithm.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Учитель?'),
        ),
    ]
