# Generated by Django 3.1 on 2020-08-18 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0005_auto_20200818_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True, max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAlgorithm.profile', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Возраст'),
        ),
    ]
