# Generated by Django 3.1 on 2020-08-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0009_auto_20200819_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(default='course_img/default_course.jpg', upload_to='course_img/', verbose_name='Превью'),
        ),
    ]
