# Generated by Django 3.1 on 2020-08-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0012_auto_20200819_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(default='WebAlgorithm/static/course_img/default_course.jpg', upload_to='WebAlgorithm/static/course_img/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(default='WebAlgorithm/static/user_img/default_user.png', upload_to='WebAlgorithm/static/user_img/', verbose_name='Фото'),
        ),
    ]
