# Generated by Django 3.1 on 2020-08-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0013_auto_20200819_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(default='course_img/default_course.jpg', storage='WebAlgorithm/static', upload_to='course_img/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(default='user_img/default_user.png', upload_to='user_img/', verbose_name='Фото'),
        ),
    ]
