# Generated by Django 3.1 on 2020-08-19 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0015_auto_20200819_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=100, verbose_name='Тема урока')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Описание урока')),
                ('attached_files', models.FileField(blank=True, upload_to='attached_files/', verbose_name='Прикрепленные файлы')),
                ('fk_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAlgorithm.course', verbose_name='Урок курса')),
            ],
        ),
    ]
