# Generated by Django 3.1 on 2020-08-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0017_auto_20200819_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.SlugField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.SlugField(max_length=100),
        ),
    ]
