# Generated by Django 3.1 on 2020-08-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0020_remove_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
