# Generated by Django 3.1 on 2020-08-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0022_auto_20200819_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
