# Generated by Django 3.1 on 2020-08-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0025_auto_20200823_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometask',
            name='HomeTask_attached_files',
            field=models.FileField(blank=True, upload_to='home_task/2020-08-23 15:47:25.601573', verbose_name='Прикрепленные файлы'),
        ),
    ]
