# Generated by Django 3.1 on 2020-08-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0026_auto_20200823_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometask',
            name='HomeTask_attached_files',
            field=models.FileField(blank=True, upload_to='home_task/', verbose_name='Прикрепленные файлы'),
        ),
    ]
