# Generated by Django 3.1 on 2020-08-25 15:51

import WebAlgorithm.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0027_auto_20200823_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='creation_data',
        ),
        migrations.AddField(
            model_name='course',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometask',
            name='deadline_time',
            field=models.DateTimeField(default=WebAlgorithm.models.week_delta, verbose_name='Дата сдачи'),
        ),
        migrations.AddField(
            model_name='hometask',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
