# Generated by Django 3.1 on 2020-08-26 13:58

import WebAlgorithm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0030_hometask_is_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometask',
            name='HomeTask_description',
        ),
        migrations.RemoveField(
            model_name='hometask',
            name='HomeTask_title',
        ),
        migrations.RemoveField(
            model_name='hometask',
            name='deadline_time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='HomeTask_description',
            field=models.TextField(default=None, max_length=100000, verbose_name='Описание задания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='HomeTask_title',
            field=models.CharField(default=None, max_length=200, verbose_name='Тема домашнего задания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='deadline_time',
            field=models.DateTimeField(default=WebAlgorithm.models.week_delta, verbose_name='Дата сдачи'),
        ),
        migrations.AlterField(
            model_name='hometask',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Сдано?d'),
        ),
    ]
