# Generated by Django 3.1 on 2020-08-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0032_auto_20200826_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='HomeTask_description',
            field=models.TextField(blank=True, default='New', max_length=100000, verbose_name='Описание задания'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='HomeTask_title',
            field=models.CharField(blank=True, default='New', max_length=200, verbose_name='Тема домашнего задания'),
        ),
    ]
