# Generated by Django 3.1 on 2020-08-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0033_auto_20200826_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='HomeTask_description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='HomeTask_title',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='deadline_time',
        ),
    ]
