# Generated by Django 3.1 on 2020-08-26 14:05

import WebAlgorithm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0034_auto_20200826_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometask',
            name='HomeTask_description',
            field=models.TextField(blank=True, default='New', max_length=100000, verbose_name='Описание задания'),
        ),
        migrations.AddField(
            model_name='hometask',
            name='HomeTask_title',
            field=models.CharField(blank=True, default='New', max_length=200, verbose_name='Тема домашнего задания'),
        ),
        migrations.AddField(
            model_name='hometask',
            name='deadline_time',
            field=models.DateTimeField(default=WebAlgorithm.models.week_delta, verbose_name='Дата сдачи'),
        ),
    ]
