# Generated by Django 3.1 on 2020-08-26 16:27

import WebAlgorithm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0038_auto_20200826_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='deadline_time',
            field=models.DateField(default=WebAlgorithm.models.week_delta, verbose_name='Дата сдачи'),
        ),
    ]
