# Generated by Django 3.1 on 2020-08-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0040_auto_20200826_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_hometask',
            field=models.BooleanField(default=False, verbose_name='Не прекреплять домашнее задание'),
        ),
    ]
