# Generated by Django 3.1 on 2020-08-31 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0041_lesson_is_hometask'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentHomeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=10000, verbose_name='Текст комментрия')),
                ('fk_home_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAlgorithm.hometask', verbose_name='Чье дз')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAlgorithm.profile', verbose_name='Кто отправил')),
            ],
        ),
    ]
