# Generated by Django 3.1 on 2020-08-31 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0042_commenthometask'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecordLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/lesson/', verbose_name='Файл')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('fk_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAlgorithm.lesson', verbose_name='Файл к уроку')),
            ],
        ),
        migrations.CreateModel(
            name='FileRecordHomeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/hometask/', verbose_name='Файл')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('fk_hometask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAlgorithm.hometask', verbose_name='Файл к д/з')),
            ],
        ),
    ]
