# Generated by Django 3.1 on 2020-08-31 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0043_filerecordhometask_filerecordlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenthometask',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hometask',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Сдано?'),
        ),
    ]
