# Generated by Django 3.1 on 2020-08-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0044_auto_20200831_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenthometask',
            name='comment_text',
            field=models.TextField(max_length=1000, verbose_name='Текст комментрия'),
        ),
    ]
