# Generated by Django 3.1 on 2020-09-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0045_auto_20200831_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filerecordlesson',
            name='fk_lesson',
        ),
        migrations.DeleteModel(
            name='FileRecordHomeTask',
        ),
        migrations.DeleteModel(
            name='FileRecordLesson',
        ),
    ]
