# Generated by Django 3.1 on 2020-10-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0047_hometask_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometask',
            name='is_allow_to_attach',
            field=models.BooleanField(default=True, verbose_name='Разрешить прикреплять дз'),
        ),
        migrations.AlterField(
            model_name='hometask',
            name='mark',
            field=models.IntegerField(blank=None, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, verbose_name='Оценка'),
        ),
    ]
