# Generated by Django 3.1 on 2020-10-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0048_auto_20201014_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometask',
            name='is_allow_to_attach',
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_allow_to_attach',
            field=models.BooleanField(default=True, verbose_name='Разрешить прикреплять дз'),
        ),
    ]
