# Generated by Django 3.1 on 2020-10-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0049_auto_20201014_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_allow_to_attach',
        ),
    ]
