# Generated by Django 3.1.3 on 2021-01-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAlgorithm', '0051_auto_20210111_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenthometask',
            name='comment_text',
            field=models.TextField(max_length=1000, verbose_name='Текст комментрия'),
        ),
    ]
